server:
  port: 9002
    
eureka:
  client:
    service-url:
      defaultZone:  http://admin:123456@localhost:8761/eureka/,http://admin:123456@localhost:8762/eureka/,http://admin:123456@localhost:8763/eureka/
  instance:
    preferIpAddress: true   #可返回IP和主机名  方法findFirstNonLoopbackAddress()获取收个非回环地址
      
feign:  
  hystrix:  
    enabled:  true
  httpclient:
    enabled: true
    
spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 10000 # 连接超时时间（毫秒）
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
        max-idle: 8 # 连接池中的最大空闲连接默认 8
        min-idle: 0 # 连接池中的最小空闲连接默认 0
    expireTime: 36000
   
auth: 熊二
redis:
  expireTime: 36000

